stages:
  - install_and_deploy

deploy:
  stage: install_and_deploy
  variables:
      RSYNC_EXCLUDES: "--exclude=.git/ --exclude=node_modules/ --exclude=.gitlab-ci.yml --exclude=.env"
  script:
    - rsync -rult --delete-after $RSYNC_EXCLUDES $CI_PROJECT_DIR/ /home/uzsuv/web/waterlab/water-site/frontend
    - cd /home/uzsuv/web/waterlab/water-site/frontend
    - nvm use 14
    - node -v 
    - yarn
    - yarn build

  tags:
    - 77uz
  timeout: 1 hour
  only:
    - master
